#!/usr/bin/env python3
"""gc.py — GC delete-list tool: explicit deletion propagation for the
no---delete star sync mesh.

Background
==========
The cross-machine agents/ sync mesh never passes ``--delete``: a file
deleted on the hub survives on every node forever, and the star hub
is purely passive (hub = NEUTRAL DIRECTORY ``/data/shared/agents`` on
the hub host — zero-originals invariant; before
that ``~/m/agents`` on dev, originally nv1). This tool is the agreed
mechanism for
propagating deletions: an EXPLICIT DELETE LIST consumed by the pull
side of ``dsync/ssh-sync.py watch`` (which excludes listed paths from
every future pull and deletes local copies).

This is a PURE CLI TOOL (user decision 2026-08-30 final): no resident
service, no snapshot diffs, no request inbox. It is invoked ON THE HUB
ONLY (the hub holds the authoritative copy; nodes receive the lists
through the normal agents/ pull) — typically by the dispatcher on user
instruction.

Layout
======
+ ``agents/gc/delete-list.<NNNNNN>``  — the lists themselves, synced
  to all nodes by the existing link. Each list is FULL & CUMULATIVE:
  it contains every currently-pending path (set semantics, naturally
  idempotent) so any node can converge from any single surviving list.
  Entry syntax (relative to ``agents/``): a plain path = one file
  a path with a trailing ``/`` = a directory subtree.
+ ``run/gc/state.json``  — hub-local deletion schedule (gitignored
  never synced): which hub copies still need deleting and when. The
  lists are the AUTHORITY and the state is a cache of the plan, so a
  lost or reset state never widens or shrinks the deletion surface —
  it only drops the plan: ``next_seq`` resumes at
  max(state, on-disk lists)+1 (no list-number collision), and the
  paths that were listed but not yet deleted stay on the hub until an
  operator re-schedules them with ``add`` (``list`` reports them, one
  line, read-only). Retiring a delete-list FILE is a ledger operation
  and happens only on ``add``'s authorized compression path.

Semantics
=========
``add``:
  1. validates every path (see the iron rules below)
  2. writes ``agents/gc/delete-list.<seq>`` atomically (tmp+rename):
     union of all surviving lists' entries ∪ the new paths ∪ the OLD
     list files themselves (LIST COMPRESSION — a new list schedules the
     deletion of its predecessors, so only the latest authoritative
     list survives long-term)
  3. schedules the hub-local deletion of the new paths AND of the old
     list files at ``now + --delay``
  4. with ``--wait``, blocks until the batch is due and performs the
     hub-local deletion before returning; without it the deletion is
     performed by the next ``add`` (which always reaps due entries
     first) or an explicit ``reap``.

``reap``:
  performs every due hub-local deletion, re-validating each entry, and
  drains it from the schedule. Nothing else: the schedule is written
  only by ``add``, so what may ever be deleted is exactly what an
  operator authorized. Idempotent — a second run finds nothing due.

The FIXED DELAY exists so the list reaches every node BEFORE the hub
copy disappears: the only resurrection vector is a node holding an
UNMARKED LOCAL ORIGINAL at a listed path (e.g. a task directory born
on that node); while the hub copy still exists, any re-push of it is
harmless, and once a node applies the list it deletes its own original
too, closing the window. Offline nodes need no delay coverage: they
neither push nor pull while offline and converge when they pull the
cumulative list later. The hub itself never pushes, so the hub residue
during the window seeds nothing.

Iron rules (enforced in code, three times: on add, on list READ /
compression ingest, AND on delete). These three hub-side checks are
the SINGLE defense line: the consumer side (dsync/ssh-sync.py) trusts
the list and applies it as-is (2026-08-31 user decision
removed the consumer-side duplicate — the lists are generated by this
single point, validated at ingest, so consumer re-checking was a
redundant layer):
+ the typed layout subtree ``bot/`` is deletable like ``task/`` and
  ``topic/`` — the bot/ immortality iron rule was REMOVED by user
  decision 2026-09-06; ``FORBIDDEN_LAYOUT_DIRS`` is now
  empty (the exemption machinery and the audited --force bypass below
  stay in place should a future exempt clan be listed)
  ``task/`` remains deletable — task dirs are ephemeral
  ``topic/`` (collaboration containers) is likewise
  deletable — topic dirs are ephemeral collaboration records

  EXCEPTION — the AUDITED FORCE BYPASS (2026-08-31 user
  decision): ``add --force`` accepts cleanup-exempt entries, but every
  such entry is stored WITH AN INLINE AUDIT MARKER
  ``<path> #FORCED:by=<who>[,task=<id>],host=<host>,ts=<UTC>`` so the
  ledger answers "who forced what when" at a glance. The marker lifts
  ONLY the exemption rule above — gc/ self-tree, absolute paths
  '..' traversal and glob metacharacters stay refused under --force.
  Read/compression and reap pass marked entries through (a legitimate
  forced entry must survive list compression; the consumer applies the
  PATH part as-is and ignores the marker — marking is hub-side audit
  not a consumer-side gate). Only ``add`` ever creates markers.
  Tradeoff, documented: a forged list could plant a forged marker and
  ride compression — accepted because (a) planting a list on a node
  that gets pushed to the hub already means a compromised node, and
  (b) the marker pins provenance for after-the-fact audit
+ paths inside ``gc/`` itself are never accepted via CLI (GC manages
  its own directory — list compression is the only internal path
  scheduling), so retiring a list file is a ledger operation that only
  ``add``'s compression step authorizes: no list content, whatever seq
  it claims, can schedule the deletion of a surviving list
+ a deletion must name a CONCRETE PARTICIPANT directory (``task/<id>/``
  ``bot/<name>/``, ``topic/<id>/``): a bare family container
  (``agents/``, ``task/``, ``bot/``, ``topic/``, ``run/``) names no
  participant and is refused — one such line would delete a whole clan
  and because the lists are cumulative and append-only it would sit in
  the ledger forever, deleting any same-named subtree the moment it
  appears. Refused like the tree-root and ``gc/`` guards, i.e. the
  audited ``--force`` bypass does NOT lift it
+ absolute paths, ``..`` elements and glob metacharacters are refused.

The read/compression filter (review finding B1) matters because a
FORGED delete-list planted on any node can reach the hub via push
``add``'s compression step would otherwise ingest its entries
unvalidated and poison every future authoritative list. The same
filter guards ``reap``'s schedule, so a tampered run/gc/state.json
cannot delete outside agents/ (review finding S1). The filter is also
how an illegal entry already sitting in an old list self-heals: it is
dropped at READ time, so the next ``add`` writes a new list without it
— the old file is never rewritten (lists are append-only), it simply
stops contributing.

Usage (ON THE HUB):
    ./gc.py add [--delay SEC] [--wait]
                [--force [--force-by NAME]] PATH [PATH ...]
    ./gc.py reap                    # perform the due hub-local deletions
    ./gc.py list                     # show lists + pending schedule
                                     # + listed-but-unscheduled paths
    (PATH is relative to agents/: a file, or a directory with a
     trailing slash, e.g. ``0828-0000-xxxx/``)

Hub directory resolution (hub neutralization): the GC
execution point stays the hub HOST (dev) but the authoritative tree
moved to the neutral directory ``/data/shared/agents``. Priority:
``GC_AGENTS_DIR`` (explicit override) > explicit ``GC_WORKSPACE``/agents
(test compatibility) > the neutral directory when it exists >
``<workspace>/agents``.

Hub zero-originals invariant: every file gc.py writes
onto the hub (the delete lists) is chgrp'd to the ``replica`` group at
write time — controlled writes are not originals.

Delay: default 300 s (production; covers worst-case multi-round
propagation incl. link flapping; offline nodes are covered by list
cumulativity instead). For testing pass ``--delay 60``.

Tests: ``python3 dsync/test_gc.py`` (self-contained, tmp dirs).
"""

import argparse
import grp
import json
import os
import re
import shutil
import socket
import sys
import tempfile
import time

_WORKSPACE = os.path.abspath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

GC_DIR_NAME = "gc"
LIST_PREFIX = "delete-list."
STATE_REL = os.path.join("run", "gc", "state.json")

DEFAULT_DELAY = 300.0  # seconds; see module docstring for rationale

# Iron rule (the bot/ clan's immortality was removed by user decision
# 2026-09-06): the typed
# layout subtree bot/ is NO LONGER immortal — it is deletable through
# the gc channel like task/ and topic/ (all three clans are ephemeral
# or explicitly-ruled purgeable; topic = collaboration containers).
# The tuple stays as the mechanism for listing any
# future cleanup-exempt clan (with the audited --force bypass below).
# Critical single assets stay protected via PROTECTED_SYSTEM_PATHS.
# HUB-SIDE ONLY defense.
FORBIDDEN_LAYOUT_DIRS = ()

# System-asset preserve list: the dispatcher
# position mailbox moved INTO the deletable topic family
# (bot/dispatcher/ -> topic/dispatcher/) when the copy-fanout channel
# forwarder was retired in favour of shared direct subscription. It is
# critical infrastructure (runner terminal notifications + child
# ask_dispatcher + human/service inform write entry; the dispatcher
# session subscribes to it via watcher/): losing it loses every task
# notification. Refused at any depth EVEN with the audited --force
# bypass — un-protecting means editing this tuple (a reviewed code
# change), not passing a CLI flag. Paths are relative to agents/
# prefix-matched on path elements ("topic/dispatcher" also protects
# "topic/dispatcher/inbox/x.msg").
# Cross-reference: the agentd side keeps the same list as
# proto.PROTECTED_SYSTEM_TOPICS / proto.PROTECTED_SYSTEM_PATHS (single source for
# report.py's system-topic exemption). This module stays stdlib-only on purpose
# (hub-side script, no repo imports), so the two copies are pinned equal by an
# e2e assertion (agentd/e2e.py S41) — adding a new system topic on only one side
# turns that check red.
#
# Live daemon bots (notify-user / heartbeat-loop / dispatcher / domain leads)
# are DELIBERATELY NOT listed here: their names live in the declaration face
# bots/daemon/, and hard-coding them into this tuple would create a second roster
# to keep in sync by hand. Their deletion guard is behavioural (cleanup tasks
# skip bot/ by default; deleting a bot needs explicit user authorisation) plus
# the auditable delete-list ledger. Ruling + re-open triggers:
# the workspace decision log.
PROTECTED_SYSTEM_PATHS = ("topic/dispatcher",)

# Hub neutral directory: the authoritative
# agents/ tree moved out of the participant workspace to this neutral
# path on the hub host (hub zero-originals invariant). Used by main
# resolution when present; GC_AGENTS_DIR / explicit GC_WORKSPACE win.
NEUTRAL_HUB_DIR = "/data/shared/agents"

# Same defense as ssh-sync's protect lists: exclude-pattern semantics
# are globs; newline would split an entry.
GLOB_UNSAFE = set("*?[\n")

# Bare family containers: the three layout clan names (same triple as
# agentd/proto.py LAYOUT_DIRS — this module stays stdlib-only, so the
# names are pinned here rather than imported) plus the tree-root-
# isomorphic ``agents`` and the workspace-level container name ``run``.
# Such an entry names NO participant, so a single line would delete an
# entire clan (or, for a same-named subtree under the tree, the whole
# tree). A deletion must name a concrete participant directory
# (``task/<id>/``, ``bot/<name>/``, ``topic/<id>/``). Structural guard:
# enforced at all three points (add / read-compression / delete) and
# NOT liftable by the audited --force bypass. Only the BARE depth-1
# container is refused — every path below it stays deletable, including
# pre-layout flat directories.
#
# Those depth-1 legacy entries (first segment is not a family container:
# pre-layout flat task dirs, participant/, ticket/, ...) stay LEGAL by design.
# Requiring two path segments would turn the existing stock into paths this
# channel can no longer delete (hand-rm only, against the deletion-channel
# iron rule) for the sole gain of a tidier ledger. Ruling + re-open triggers:
# the workspace decision log.
BARE_FAMILY_ENTRIES = ("agents", "task", "bot", "topic", "run")

# Audited force bypass (2026-08-31 user decision): the
# inline marker that ``add --force`` appends to cleanup-exempt entries
# so the delete-list ledger records WHO forced WHAT WHEN. Duplicated
# verbatim in ssh-sync.py (consumer strips it to get the path).
FORCE_MARK = " #FORCED:"
# Audit field values must stay in this alphabet (no spaces, no '/';
# the entry must stay one line and one rsync-safe path).
_FORCE_AUDIT_SAFE = re.compile(r"^[A-Za-z0-9._:@+=,-]+$")


class GcError(Exception):
    pass


def split_force(e):
    """Split an entry into (path, audit-or-None) at the FORCE_MARK
    marker. Entries without the marker return
    (e, None). Only ``add --force`` writes marked entries; read /
    compression / reap pass them through."""
    i = e.find(FORCE_MARK)
    if i < 0:
        return e, None
    return e[:i], e[i + len(FORCE_MARK):]


def validate_entry(e):
    """Structural (no-filesystem) validation of one delete-list entry
    string as written in a list file or a schedule. Returns None when
    legal, else a human-readable reason. Enforces the iron rules and
    the gc/ self-tree guard; the ONLY legal gc/ entry is a compression
    entry (plain file entry ``gc/delete-list.NNNNNN``).

    An entry carrying the FORCE_MARK audit marker (``add --force``
    output) is exempted from the cleanup-exemption iron
    rule (FORBIDDEN_LAYOUT_DIRS) — every other check applies
    unchanged, and the audit string must be non-empty and
    alphabet-safe."""
    e, mark = split_force(e)
    if mark is not None and not _FORCE_AUDIT_SAFE.match(mark):
        return "malformed or empty force-audit marker"
    return validate_path(e, force=mark is not None)


def validate_path(e, force=False):
    """Core structural validation of one entry PATH (no marker).
    ``force=True`` lifts ONLY the cleanup-exemption iron rule."""
    if not e or e != e.strip():
        return "empty or unstripped entry"
    if e.startswith("/"):
        return "absolute paths are not allowed"
    if any(c in GLOB_UNSAFE for c in e):
        return "glob-unsafe characters are not allowed"
    raw = e.rstrip("/")
    is_dir = e.endswith("/")
    if not raw or raw == ".":
        return "refusing the tree root"
    parts = raw.split("/")
    if any(p in ("", "..") for p in parts):
        return "empty or '..' path elements are not allowed"
    if len(parts) == 1 and parts[0] in BARE_FAMILY_ENTRIES:
        return (f"{parts[0]}/ is a BARE FAMILY CONTAINER — it names no "
                "participant; a deletion must name a concrete participant "
                "directory (task/<id>/, bot/<name>/, topic/<id>/). "
                "Refused even with --force; un-refuse = edit "
                "BARE_FAMILY_ENTRIES in dsync/gc.py")
    for prot in PROTECTED_SYSTEM_PATHS:
        pp = prot.strip("/").split("/")
        if parts[:len(pp)] == pp:
            return (f"{prot}/ is a PROTECTED system asset (dispatcher "
                    "position mailbox) — deletion refused "
                    "even with --force; un-protect = edit "
                    "PROTECTED_SYSTEM_PATHS in dsync/gc.py")
    top = parts[0]
    if top in FORBIDDEN_LAYOUT_DIRS and not force:
        return (f"the {top}/ layout subtree is NEVER deletable "
                "(iron rule, cleanup-exemption law; audited bypass: "
                "add --force)")
    if top == GC_DIR_NAME:
        if len(parts) == 2 and parts[1].startswith(LIST_PREFIX) \
                and not is_dir:
            return None  # list compression entry: legal
        return f"the {GC_DIR_NAME}/ tree is managed by gc.py itself"
    return None


def sanitize_entry(raw, agents_dir=None, force=False):
    """Validate one CLI path argument. Returns the normalized entry
    string (directory entries carry exactly one trailing slash).
    Raises GcError with a human-readable reason on any violation.

    ``force=True`` (``add --force``) lifts ONLY the
    cleanup-exemption iron rule; every other check stays. The caller
    attaches the FORCE_MARK audit marker afterwards.

    With ``agents_dir`` given (the production CLI path), an unslashed
    path that points at an EXISTING directory is auto-normalized to a
    subtree entry (``dir/``) — a file entry for a directory would make
    the consumer os.remove a directory (OSError every cycle, never
    converging bug2)."""
    e = raw.strip()
    if not e:
        raise GcError("empty path")
    why = validate_path(e, force=force)
    if why:
        raise GcError(f"{raw!r}: {why}")
    if agents_dir is not None and not e.endswith("/"):
        p = os.path.join(agents_dir, e)
        if os.path.isdir(p):
            e += "/"
    return e


def entry_to_relpath(entry):
    """Entry string -> relative path without trailing slash (the
    FORCE_MARK audit marker, if any, is stripped first)."""
    return split_force(entry)[0].rstrip("/")


def resolved_target(agents_dir, entry):
    """Entry -> resolved ABSOLUTE path (echo hardening).
    Read-only: resolves, never creates. Ledger entries are relative to the
    agents/ tree root (see the Layout section of this docstring), so the honest
    echo is agents_dir + entry, realpath'd — the hub tree is usually the neutral
    directory (data/shared/agents), NOT the caller's workspace, and a relative
    echo hides which tree the deletion will actually happen in."""
    return os.path.realpath(os.path.join(agents_dir, entry_to_relpath(entry)))


def wrong_basis_warn(agents_dir, entry):
    """One-line WARN when an entry's literal first segment is ``agents/`` — the
    signature of writing a WORKSPACE-relative path into a ledger whose basis is
    the AGENTS tree (wrong basis; 2026-09-15 instance: an operator passed
    ``agents/bot/<name>/control/`` and two control requests stayed invisible in a
    nested tree that nobody consumes). Returns None when the entry is fine.
    Warning only: validation, scheduling and deletion semantics are untouched."""
    rel = entry_to_relpath(entry)
    if rel.split("/")[0] != "agents":
        return None
    return (f"WARN: entry {entry!r} begins with a literal 'agents/' segment, but "
            f"delete-list entries are relative to the agents/ tree "
            f"({os.path.realpath(agents_dir)}) — it resolves to "
            f"{resolved_target(agents_dir, entry)}, which is almost certainly not "
            f"what you meant (wrong basis: drop the leading 'agents/' -> "
            f"{rel[len('agents/'):]!r})")


def make_force_mark(forced_by):
    """Audit marker payload for ``add --force``: who
    authorized the exempt-area deletion, from which task/host, when
    (UTC). Alphabet-safe by construction (validated upstream).
    AGENT_SELF arrives path-style (``task/<id>``, bot layout era) and
    the marker alphabet forbids ``/`` — transcribe per the fsSafeId
    convention (``/`` → ``.``)."""
    parts = [f"by={forced_by}"]
    task = os.environ.get("AGENT_SELF")
    if task:
        parts.append("task=" + task.replace("/", "."))
    parts.append(f"host={socket.gethostname()}")
    parts.append("ts=" + time.strftime("%Y-%m-%dT%H:%M:%SZ",
                                       time.gmtime()))
    return ",".join(parts)


def list_dir(agents_dir):
    return os.path.join(agents_dir, GC_DIR_NAME)


def existing_lists(agents_dir):
    """Sorted list of delete-list filenames (relative to agents/:
    'gc/delete-list.000001')."""
    d = list_dir(agents_dir)
    try:
        names = [f for f in sorted(os.listdir(d))
                 if f.startswith(LIST_PREFIX)]
    except OSError:
        names = []
    return [os.path.join(GC_DIR_NAME, f) for f in names]


# One warning per distinct pollution signature per invocation (see
# ``read_entries``): this tool is a short-lived CLI, so process scope ==
# invocation scope.
_SKIP_REPORTED = set()


def read_entries(agents_dir):
    """Union of entries across all surviving delete-list files, in
    first-seen order. Best-effort per file (unreadable file = skipped
    this round; lists are written atomically). Entries keep their
    FORCE_MARK audit marker so compression carries the
    audit trail forward; dedup is by PATH part, a marked entry
    supersedes an unmarked duplicate.

    Illegal entries are dropped here (so they cannot ride compression
    into the next authoritative list) and reported as ONE summary line
    not one line per entry — and the same pollution is reported only
    ONCE PER INVOCATION: every ``reap``/``add``/``list`` re-reads all
    surviving lists (``list`` reads them twice), so a polluted ledger
    would otherwise repeat the same warnings several times per round.
    The samples keep it auditable, the cap keeps it quiet, and a CHANGE
    in the polluted set (new entries) is a new signature and reports
    again."""
    best = {}
    order = []
    skipped = []
    d = list_dir(agents_dir)
    for fn in sorted(os.listdir(d)) if os.path.isdir(d) else []:
        if not fn.startswith(LIST_PREFIX):
            continue
        try:
            with open(os.path.join(d, fn), encoding="utf-8") as fh:
                for line in fh:
                    e = line.strip()
                    if not e or e.startswith("#"):
                        continue
                    why = validate_entry(e)
                    if why:
                        # Forged/malformed entries (e.g. planted on a
                        # node and pushed back) must NOT ride along
                        # into the next authoritative list via
                        # compression — filter at READ time. (Entries
                        # carrying a FORCE_MARK audit marker pass here
                        # by design: legitimate forced
                        # entries must survive compression; a forged
                        # marker is the documented tradeoff, provenance
                        # stays auditable.)
                        skipped.append((e, fn, why))
                        continue
                    path, mark = split_force(e)
                    if path in best:
                        # Duplicate path: a MARKED entry supersedes an
                        # unmarked one (audit trail wins).
                        if mark and not split_force(best[path])[1]:
                            best[path] = e
                        continue
                    best[path] = e
                    order.append(path)
        except OSError:
            continue
    if skipped:
        distinct = {}
        for e, fn, why in skipped:
            distinct.setdefault(e, (fn, why))
        cap = 5
        samples = "; ".join(f"{e!r} in {fn}: {why}"
                            for e, (fn, why)
                            in list(distinct.items())[:cap])
        more = (f"; +{len(distinct) - cap} more distinct"
                if len(distinct) > cap else "")
        sig = (agents_dir, tuple(sorted(distinct)))
        if sig not in _SKIP_REPORTED:
            _SKIP_REPORTED.add(sig)
            print(f"read_entries: SKIPPED {len(skipped)} illegal "
                  f"{'entry' if len(skipped) == 1 else 'entries'} "
                  f"({len(distinct)} distinct) in the surviving lists: "
                  f"{samples}{more}", file=sys.stderr)
    return [best[p] for p in order]


def state_path(ws):
    return os.path.join(ws, STATE_REL)


def load_state(ws):
    """{'seq': int, 'schedule': {entry: due_ts}}; tolerant of a lost or
    corrupt file (``next_seq`` resumes from the on-disk lists, so a lost
    state cannot collide with a surviving list). Keys this tool no longer
    uses are dropped, so the file converges on the next save."""
    default = {"seq": 0, "schedule": {}}
    p = state_path(ws)
    try:
        with open(p, encoding="utf-8") as fh:
            st = json.load(fh)
        if not isinstance(st, dict):
            return default
        return {"seq": st.get("seq", 0),
                "schedule": st.get("schedule", {})}
    except (OSError, ValueError):
        return default


def save_state(ws, st):
    p = state_path(ws)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(p), prefix=".state.")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            json.dump(st, fh, indent=1, sort_keys=True)
        os.rename(tmp, p)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def next_seq(st, agents_dir):
    """Monotone seq: max(state, max existing list on disk) + 1 — so a
    lost state file cannot collide with a surviving list."""
    mx = int(st.get("seq", 0))
    for lp in existing_lists(agents_dir):
        try:
            mx = max(mx, int(lp.rsplit(".", 1)[1]))
        except (ValueError, IndexError):
            continue
    return mx + 1


def _tag_replica(path):
    """Hub zero-originals invariant: every file gc.py
    writes onto the hub is a CONTROLLED write and must land with the
    replica group, like any synced replica. Best-effort: warn (not
    fatal) if the replica group is unavailable."""
    try:
        os.chown(path, -1, grp.getgrnam("replica").gr_gid)
    except (KeyError, OSError) as e:
        print(f"gc: warning: cannot tag {path} with the replica "
              f"group: {e}", file=sys.stderr)


def write_list(agents_dir, seq, entries):
    """Atomically write agents/gc/delete-list.<seq> (tmp+rename)."""
    d = list_dir(agents_dir)
    os.makedirs(d, exist_ok=True)
    name = f"{LIST_PREFIX}{seq:06d}"
    fd, tmp = tempfile.mkstemp(dir=d, prefix=f".{name}.")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            for e in entries:
                fh.write(e + "\n")
        final = os.path.join(d, name)
        os.rename(tmp, final)
        _tag_replica(final)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise
    return os.path.join(GC_DIR_NAME, name)


def resolve_agents_dir(ws):
    """Hub agents/ tree resolution: GC_AGENTS_DIR
    (explicit) > explicit GC_WORKSPACE/agents (test compat) > the
    neutral hub directory when it exists > <workspace>/agents."""
    env = os.environ.get("GC_AGENTS_DIR")
    if env:
        return os.path.abspath(env)
    if os.environ.get("GC_WORKSPACE"):
        return os.path.join(ws, "agents")
    if os.path.isdir(NEUTRAL_HUB_DIR):
        return NEUTRAL_HUB_DIR
    return os.path.join(ws, "agents")


def is_forbidden_at_delete(rel):
    """Second-line check right before any hub-local deletion (defense
    in depth). Since (review finding S1) this is
    the FULL entry validation — iron-rule prefixes AND gc/ self-tree
    AND absolute paths / '..' traversal / glob metacharacters — so a
    tampered run/gc/state.json cannot delete outside agents/."""
    return validate_entry(rel) is not None


def _list_seq(list_rel):
    """Numeric seq of a delete-list path ('gc/delete-list.000042' -> 42),
    -1 when unparsable. Numeric rather than lexicographic so the
    ordering stays correct past six digits."""
    try:
        return int(list_rel.rsplit(".", 1)[1])
    except (ValueError, IndexError):
        return -1


def reap(ws, agents_dir, now=None, verbose=True):
    """Perform every due hub-local deletion. Returns (deleted, missed).
    Never fatal: per-path errors are reported and retried next round.

    The schedule is written ONLY by ``add``, so this can never delete
    anything an operator did not authorize; a lost or reset state simply
    means nothing is due (``list`` reports the listed-but-unscheduled
    residue, and re-running ``add`` on those paths re-plans them)."""
    now = time.time() if now is None else now
    st = load_state(ws)
    sched = st.get("schedule", {})
    deleted, missed = [], []
    refused = 0
    for entry in sorted(e for e, due in sched.items() if due <= now):
        why = validate_entry(entry)
        if why:
            # Full re-validation at delete time: add refuses these, so
            # reaching here means a tampered state.json — refuse
            # loudly and DROP the entry so it cannot retry forever.
            # (FORCE_MARK-marked entries validate here by design:
            # only add --force writes them into the schedule.)
            print(f"reap: REFUSING invalid schedule entry {entry!r}: "
                  f"{why}", file=sys.stderr)
            sched.pop(entry, None)
            refused += 1
            continue
        rel = entry_to_relpath(entry)
        p = os.path.join(agents_dir, rel)
        try:
            if entry.endswith("/"):
                if os.path.islink(p):
                    # Symlink: consume the link itself (the target
                    # survives); the entry converges (review S2).
                    os.remove(p)
                    deleted.append(entry)
                elif os.path.isdir(p):
                    shutil.rmtree(p)
                    deleted.append(entry)
                elif os.path.lexists(p):
                    # Type mismatch (dir entry at a plain file): remove
                    # it so the entry converges instead of retrying
                    # forever (bug2/S2 policy).
                    print(f"reap: warning: {entry!r}: directory entry "
                          "at a plain file; removing the file",
                          file=sys.stderr)
                    os.remove(p)
                    deleted.append(entry)
                else:
                    deleted.append(entry)  # already gone = converged
            else:
                if os.path.islink(p):
                    os.remove(p)
                    deleted.append(entry)
                elif os.path.isdir(p):
                    # Type mismatch (file entry at a directory, e.g. an
                    # unslashed dir path from a pre-bug2-fix list):
                    # remove the subtree so the chain converges.
                    print(f"reap: warning: {entry!r}: file entry at a "
                          "directory; removing the subtree",
                          file=sys.stderr)
                    shutil.rmtree(p)
                    deleted.append(entry)
                elif os.path.lexists(p):
                    os.remove(p)
                    deleted.append(entry)
                else:
                    deleted.append(entry)  # already gone = converged
            sched.pop(entry, None)
        except OSError as e:
            missed.append((entry, str(e)))
    if deleted or missed or refused:
        save_state(ws, st)
    if verbose:
        for e in deleted:
            print(f"reap: deleted {e}")
        for e, why in missed:
            print(f"reap: FAILED {e}: {why}", file=sys.stderr)
    return deleted, missed


def cmd_add(ws, agents_dir, paths, delay, wait, force=False,
            forced_by=None):
    # Keep the schedule honest first: delete whatever is already due.
    reap(ws, agents_dir, verbose=True)

    # --force: user-authorized deletion of cleanup-exempt
    # areas. Only the exemption iron rule is lifted; entries that
    # needed the bypass carry the FORCE_MARK audit marker in the list
    # (who/when/where forced what). Regular entries are never marked.
    mark = make_force_mark(forced_by) if force else None

    entries_new = []
    for p in paths:
        try:
            e = sanitize_entry(p, agents_dir, force=force)
        except GcError as why:
            print(f"add: REJECTED {why}", file=sys.stderr)
            return 1
        if mark and validate_path(e, force=False):
            # Would have been refused without --force -> exempt-area
            # entry -> must carry the audit marker in the ledger.
            e += FORCE_MARK + mark
        # Echo hardening: show the RESOLVED absolute target before
        # anything is written, plus a wrong-basis WARN for a literal 'agents/'
        # first segment. Echo only — the entry string and the deletion semantics
        # are unchanged.
        print(f"add: entry {e!r} -> {resolved_target(agents_dir, e)}")
        w = wrong_basis_warn(agents_dir, e)
        if w:
            print(w, file=sys.stderr)
        entries_new.append(e)
    if not entries_new:
        print("add: nothing to add", file=sys.stderr)
        return 1

    st = load_state(ws)
    old_lists = existing_lists(agents_dir)
    union = read_entries(agents_dir)
    have = {}  # path part -> index in union (marker-aware dedup)
    for i, e in enumerate(union):
        have[split_force(e)[0]] = i
    for e in entries_new:
        path, new_mark = split_force(e)
        if path not in have:
            have[path] = len(union)
            union.append(e)
        elif new_mark and not split_force(union[have[path]])[1]:
            union[have[path]] = e  # marked supersedes unmarked
    for lp in old_lists:
        if lp not in have:
            have[lp] = len(union)
            union.append(lp)  # compression: new list deletes old lists

    seq = next_seq(st, agents_dir)
    written = write_list(agents_dir, seq, union)
    print(f"add: wrote agents/{written} ({len(union)} entries, "
          f"{len(entries_new)} new, compressing {len(old_lists)} old "
          f"list(s))")

    now = time.time()
    due = now + delay
    sched = st.setdefault("schedule", {})
    batch_due = []
    for e in entries_new:
        if e not in sched:
            sched[e] = due
        batch_due.append(sched[e])
    for lp in old_lists:
        if lp not in sched:
            sched[lp] = due
        batch_due.append(sched[lp])
    st["seq"] = seq
    save_state(ws, st)
    print(f"add: scheduled {len(batch_due)} hub-local deletion(s) due "
          f"in {delay:.0f}s")

    if wait:
        target = max(batch_due) if batch_due else now
        remain = target - time.time()
        if remain > 0:
            print(f"add: --wait: sleeping {remain:.0f}s until due ...")
            time.sleep(remain)
        deleted, missed = reap(ws, agents_dir, verbose=True)
        if missed:
            print(f"add: {len(missed)} deletion(s) failed (see above); "
                  "retry with `reap`", file=sys.stderr)
            return 1
    return 0


def cmd_reap(ws, agents_dir):
    deleted, missed = reap(ws, agents_dir, verbose=True)
    if not deleted and not missed:
        print("reap: nothing due")
    return 1 if missed else 0


def cmd_list(ws, agents_dir):
    # Echo hardening: pin the BASIS first (every entry below is
    # relative to it), then echo each pending entry with its resolved absolute
    # target and a wrong-basis WARN for a literal 'agents/' first segment.
    # Read-only: no state change, no grace clock, deletion semantics untouched.
    print(f"agents tree (realpath): {os.path.realpath(agents_dir)}")
    lists = existing_lists(agents_dir)
    print(f"lists ({len(lists)}):")
    for lp in lists:
        p = os.path.join(agents_dir, lp)
        try:
            n = sum(1 for ln in open(p, encoding="utf-8") if ln.strip())
        except OSError:
            n = -1
        print(f"  agents/{lp}  ({n} entries)")
    entries = read_entries(agents_dir)
    print(f"union: {len(entries)} pending path(s)")
    for e in entries:
        print(f"  {e}  -> {resolved_target(agents_dir, e)}")
        w = wrong_basis_warn(agents_dir, e)
        if w:
            print(w, file=sys.stderr)
    st = load_state(ws)
    sched = st.get("schedule", {})
    now = time.time()
    print(f"schedule ({len(sched)} pending hub-local deletion(s)):")
    for e, due in sorted(sched.items(), key=lambda kv: kv[1]):
        remain = due - now
        print(f"  {e}  due in {remain:.0f}s"
              if remain > 0 else f"  {e}  DUE NOW")
    # READ-ONLY symptom report: listed paths that are still present here
    # and have no schedule entry. Normal right after a state loss (the
    # plan is a cache); the fix is an explicit `add` of those paths, so
    # nothing here mutates the state or starts a grace clock.
    scheduled = {entry_to_relpath(k) for k in sched}
    residue = [e for e in entries
               if entry_to_relpath(e) not in scheduled
               and not entry_to_relpath(e).startswith(GC_DIR_NAME + "/")
               and os.path.lexists(os.path.join(
                   agents_dir, entry_to_relpath(e)))]
    print(f"unscheduled ({len(residue)} listed path(s) still present "
          f"here with no plan; re-run `gc.py add <path>` to schedule "
          f"them):")
    for e in residue:
        print(f"  {e}")
    return 0


def main(argv=None):
    ws = os.environ.get("GC_WORKSPACE") or _WORKSPACE
    agents_dir = resolve_agents_dir(ws)

    p = argparse.ArgumentParser(
        description="GC delete-list tool: propagate agents/ deletions "
                    "to all sync-mesh nodes via explicit cumulative "
                    "delete lists (run ON THE HUB only).")
    sub = p.add_subparsers(dest="cmd", required=True)

    sp = sub.add_parser("add", help="add paths to a new delete-list")
    sp.add_argument("paths", nargs="+", metavar="PATH",
                    help="path relative to agents/ (trailing slash = "
                         "directory subtree)")
    sp.add_argument("--delay", type=float, default=DEFAULT_DELAY,
                    metavar="SEC",
                    help=f"fixed delay before hub-local deletion "
                         f"(default {DEFAULT_DELAY:.0f}s)")
    sp.add_argument("--wait", action="store_true",
                    help="block until due and perform the hub-local "
                         "deletion before returning")
    sp.add_argument("--force", action="store_true",
                    help="AUDITED BYPASS (2026-08-31 "
                         "user decision): accept cleanup-exempt paths "
                         "(FORBIDDEN_LAYOUT_DIRS; currently empty — "
                         "bot/ immortality removed 2026-09-06). "
                         "Every exempt entry is recorded with "
                         "an inline '#FORCED:' audit marker (who/"
                         "when/where). Lifts ONLY the exemption iron "
                         "rules — all other validation unchanged. Use "
                         "only for USER-AUTHORIZED exempt-area "
                         "deletions.")
    sp.add_argument("--force-by", default=None, metavar="NAME",
                    help="who authorized the forced deletion "
                         "(default: $USER); stored in the audit "
                         "marker")

    sub.add_parser("reap", help="perform the due hub-local deletions "
                                "(the schedule is written by `add`)")
    sub.add_parser("list", help="show lists and pending schedule")

    args = p.parse_args(argv)

    if not os.path.isdir(agents_dir):
        print(f"gc: error: {agents_dir} not found (is GC_AGENTS_DIR / "
              f"GC_WORKSPACE correct?)", file=sys.stderr)
        return 1

    if args.cmd == "add":
        forced_by = args.force_by or os.environ.get("USER", "unknown")
        if args.force and not _FORCE_AUDIT_SAFE.match(forced_by):
            print("gc: error: --force-by must match "
                  f"{_FORCE_AUDIT_SAFE.pattern}", file=sys.stderr)
            return 1
        return cmd_add(ws, agents_dir, args.paths, args.delay,
                       args.wait, force=args.force, forced_by=forced_by)
    if args.cmd == "reap":
        return cmd_reap(ws, agents_dir)
    if args.cmd == "list":
        return cmd_list(ws, agents_dir)
    return 2


if __name__ == "__main__":
    sys.exit(main())
